@startuml 用例图
!include style.puml
left to right direction
actor 遗失物品者
actor 捡拾物品者
rectangle 失物招领APP {
  遗失物品者 -- (查询捡拾物品列表)
  遗失物品者 -- (查询遗失物品列表)
  遗失物品者 -- (失而复得登记)
  遗失物品者 -- (遗失物品登记)
  遗失物品者 -- (遗失物品信息修改)
  (遗失物品登记) .> (物品信息语义分析并归类) : include
  (查询捡拾物品列表) .> (推荐捡拾物品列表) : extends
  (捡拾物品信息修改) -- 捡拾物品者
  (捡拾物品登记) -- 捡拾物品者
  (查询遗失物品列表) -- 捡拾物品者
  (查询捡拾物品列表) -- 捡拾物品者
  (捡拾物品信息修改) .> (物品信息语义分析并归类) : include
  (捡拾物品登记) .> (物品信息语义分析并归类) : include
  (捡拾物品信息修改) .> (捡拾证件图片自动打码) : extends
  (捡拾物品登记) .> (捡拾证件图片自动打码) : extends
  
}
@enduml